import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Leah Livingston Full Stack Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{`Leah Livingston's Portfolio`}</h1>
      <div>
        <div>
        ![Loading](../public/loading.gif)
        </div>
        <div>
          Check out my resume here{' '}
              <a
                href="https://drive.google.com/file/d/1k-X3cNCU5G22tQ279Nh70rlOKLVQjgeM/view?usp=drive_link"
                target="_blank"
                rel="noopener noreferrer"
              >
              Resume on Google Drive
            </a>
        </div>
      </div>
    </>
  )
}
