import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Leah Livingston</title>
        <h1>Full Stack Software Engineer & Data Analyst</h1>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>
        body {
          background-image: url('/clouds.jpeg');
          background-size: cover;
          background-repeat: no-repeat;
          margin: 0; 
          padding: 0; 
          font-family: ${inter}; 
        }
      </style>
      <h1>{`Leah Livingston's Portfolio`}</h1>
      <div>
        <div className={styles.imageContainer}>
          <Image 
              src="/loading.gif"
              alt="Loading"
              width={100}
              height={50}
            />
        </div>
        <div>
          ** Ojé... you caught this site under construction. Please come back later. **
        </div>
        <div>
          And in the meantime, see my resume here ➡️ {' '}
              <a
                href="https://drive.google.com/file/d/1k-X3cNCU5G22tQ279Nh70rlOKLVQjgeM/view?usp=drive_link"
                target="_blank"
                rel="noopener noreferrer"
              >
              Download from Google Drive
            </a>
        </div>
      </div>
    </>
  )
}
